/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormBuilderRouteImport } from './routes/_form-builder'
import { Route as FormBuilderCreateRouteImport } from './routes/_form-builder/create'
import { Route as FormBuilderEditRouteImport } from './routes/_form-builder/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/_form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderCreateRoute = FormBuilderCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FormBuilderRoute,
} as any)
const FormBuilderEditRoute = FormBuilderEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FormBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof FormBuilderCreateRoute
  '/edit': typeof FormBuilderEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof FormBuilderCreateRoute
  '/edit': typeof FormBuilderEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_form-builder': typeof FormBuilderRouteWithChildren
  '/_form-builder/create': typeof FormBuilderCreateRoute
  '/_form-builder/edit': typeof FormBuilderEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/edit'
  id:
    | '__root__'
    | '/'
    | '/_form-builder'
    | '/_form-builder/create'
    | '/_form-builder/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form-builder': {
      id: '/_form-builder'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form-builder/create': {
      id: '/_form-builder/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof FormBuilderCreateRouteImport
      parentRoute: typeof FormBuilderRoute
    }
    '/_form-builder/edit': {
      id: '/_form-builder/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof FormBuilderEditRouteImport
      parentRoute: typeof FormBuilderRoute
    }
  }
}

interface FormBuilderRouteChildren {
  FormBuilderCreateRoute: typeof FormBuilderCreateRoute
  FormBuilderEditRoute: typeof FormBuilderEditRoute
}

const FormBuilderRouteChildren: FormBuilderRouteChildren = {
  FormBuilderCreateRoute: FormBuilderCreateRoute,
  FormBuilderEditRoute: FormBuilderEditRoute,
}

const FormBuilderRouteWithChildren = FormBuilderRoute._addFileChildren(
  FormBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
